### ISSUE TITLE
Google font inclusion not properly recognized

### ISSUE THREAD

**Issue by xorx1** [JoomTools/plg_system_jtaldef#1]
This font is not properly cached:
`https://fonts.googleapis.com/css2?family=Dosis:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800&display=swap

While this font is cached:
`https://fonts.googleapis.com/css?family=Open+Sans:300

Any idea how to fix this?

Regards, XorX

**Comment by degobbis** [comment]
Hi XorX,

checking on GoogleFont, I found that there is no variation 'italic' for the font to download, so it cannot be downloaded.

**Comment by xorx1** [comment]
Thank you! In deed I did not see, that this font-type is not available.
