### ISSUE TITLE
Google Search Console «Nutzerfreundlichkeit auf Mobilgeräten»

### ISSUE THREAD

**Issue by crimle** [JoomTools/plg_system_jtaldef#11]
Seit ich das Plugin «JT - ALDEF» verwende, meldet mir die «Google Search Console» bei praktisch allen Webseiten
**Probleme vom Typ «Nutzerfreundlichkeit auf Mobilgeräten» erkannt**
- Text ist zu klein zum Lesen
- Anklickbare Elemente liegen zu dicht beieinander

Ursache: Google konnte zwei CSS-Dateien (gekennzeichnet mit «processed by JT - ALDEF») nicht verarbeiten. Eine CSS-Datei war vom «DJ-ImageSlider» und eine zweite vom «JCE Content Editor». Den genauen Grund dafür kenne ich natürlich nicht.

Das Deaktivieren des Plugins «JT - ALDEF» hat das Problem sofort beseitigt.

Vielleicht kann dieses Problem in einer zukünftigen Version von «JT - ALDEF» behoben werden. Vielen Dank!

**Comment by degobbis** [comment]
Die Meldung ist etwas irritierend und könnte auch eine False Positive sein.
Gerade bei der vom JCE weiss ich, dass die von mir nicht angefasst wird, es wird nur mein Attribut hinzugefügt.
Damit stelle ich nur sicher, dass diese datei von meinem Plugin auch berücksichtigt wurde.
Verändert sich denn auf Mobilgeräten die Darstellung der Schrift, wenn mein Plugin aus ist?

**Comment by crimle** [comment]
Ich vermute, das Problem mit JCE kommt nur zum Tragen, wenn auf der Seite gleichzeitig der «DJ-ImageSlider» angezeigt wird. Alle anderen Seiten sind gemäss Google ok, nur die Startseite nicht.

Die Option «Auch lokale CSS-Dateien» = «Nein» habe ich auch ausprobiert. Sie reicht nicht aus. Der Fehler ist erst weg, wenn ich das Plugin ganz deaktiviere. «Zurücksetzen» habe ich gemacht.

Die Schrift verändert sich nicht, wenn ich das Plugin deaktiviere.

**Comment by crimle** [comment]
Hier die betroffenen drei Dateien:
modules/mod_djimageslider/assets/js/slider.js?v=4.4
modules/mod_djimageslider/themes/default/css/djimageslider.css
plugins/system/jce/css/content.css?badb4208be409b1335b815dde676300e

**Comment by degobbis** [comment]
Das könnte mit der robots.txt zu tun haben.
Da wird den Bots nicht erlaubt auf dateien dieser Ordner zuzugreifen.
Warum es aber bei abgeschaltetem Plugin keine Meldung gibt, ist mir ein Rätsel.
Womöglich stöst sich der Bot an meinem Attribut `data-jtaldef-processed`.
Du könntest das in der folgenden Plugindatei mal durch Suchen und Ersetzen ändern und sehen was passiert:
https://github.com/joomtools/plg_system_jtaldef/blob/master/src/plugins/system/jtaldef/jtaldef.php

**Comment by crimle** [comment]
Ich bin etwas unsicher, da ich keine Programmierkenntnisse habe. Muss ich nach «data-jtaldef-processed» suchen und alle Vorkommnisse durch «» ersetzen?

**Comment by degobbis** [comment]
Es sollte reichen, wenn Du nach -processed suchst und mit nichts ersetzt.

**Comment by degobbis** [comment]
Gibt es schon was neues bei Dir?
Besteht das Problem noch mit der Version 2.0.7?
