### ISSUE TITLE
[2.0.6] Plugin misses Roboto font and generates two identical css files

### ISSUE THREAD

**Issue by Heart1010** [JoomTools/plg_system_jtaldef#12]
Using the latest v2.0.6 and have 'strange behaviour' with one of my sites.

I have two google fonts.. 
![image](https://user-images.githubusercontent.com/1481680/221931619-940669f1-385a-4321-914d-336d89c1cbf1.png)
The template generated that two google fonts in ONE line in the source code - I thought that this causes problems?!

So I changed the template source code so it looks now 
![image](https://user-images.githubusercontent.com/1481680/221931866-57604615-28bf-49fb-8c58-dac5222e6fab.png)

Then I activated the joomla plugin and refreshed the homepage - and I end up with identical css files?!
![image](https://user-images.githubusercontent.com/1481680/221932266-1433e013-f88b-4154-81fc-16a012148fff.png)

These jtaldef generated css file only includes Open Sans but not Roboto
![image](https://user-images.githubusercontent.com/1481680/221932538-5c991db4-497b-4427-a54a-3ae0aff9b5b1.png)

The Roboto font itself is correct inside the media folder (but jtaldef doesn't include it in its css file)?!
![image](https://user-images.githubusercontent.com/1481680/221933291-397d450e-7eb5-4481-b45d-75cc91eee412.png)

![image](https://user-images.githubusercontent.com/1481680/221932200-2415e3da-175e-4676-9445-53c92b22956c.png)

**Comment by degobbis** [comment]
Confirmed and fixed with version 2.0.7

**Comment by degobbis** [comment]
Thx
