### ISSUE TITLE
Plugin prevents Balbooa Joomla Forms Builder from working properly

### ISSUE THREAD

**Issue by crimle** [JoomTools/plg_system_jtaldef#14]
The plugin «System - JT - ALDEF 2.0.7» prevents any webforms created by the extension «Balbooa Joomla Forms Builder» from working properly. The submit button of these forms seems to be disabled. Clicking the button makes the form to move upwards a little bit. That's it, the form is not being sent. 

I fallbacked to «System - JT - ALDEF 2.0.5» which is ok.

**Comment by degobbis** [comment]
Maybe the test version from Issue #13 solves this problem as well?

**Comment by crimle** [comment]
Unfortunately, plg_system_jtaldef-2.0.8-dev.zip does NOT resolve this issue.

**Comment by degobbis** [comment]
Ok, I think I have found the bug.
Please test this: 
[plg_system_jtaldef-2.0.8-rc1.zip](https://github.com/joomtools/plg_system_jtaldef/files/11044912/plg_system_jtaldef-2.0.8-rc1.zip)

**Comment by crimle** [comment]
Installing this plg_system_jtaldef-2.0.8-rc1.zip results in the following error message:
JInstaller: :Install: Die Datei „[ROOT][TMP]/install_641c5f15c375c/media/plg_system_jtaldef/index“ existiert nicht.

**Comment by degobbis** [comment]
Sorry for the Error, this version is fixed:
[plg_system_jtaldef-2.0.8-rc2.zip](https://github.com/joomtools/plg_system_jtaldef/files/11052110/plg_system_jtaldef-2.0.8-rc2.zip)

**Comment by crimle** [comment]
I am happy to report that plg_system_jtaldef-2.0.8-rc2.zip resolves the issue.
Thank you very much and kind regards
Chris

**Comment by degobbis** [comment]
Thx for reporting.
