### ISSUE TITLE
Warning: Illegal string offset 

### ISSUE THREAD

**Issue by crimle** [JoomTools/plg_system_jtaldef#15]
After installing plg_system_jtaldef-2.0.8 I see the following message on some of my websites:
`Warning: Illegal string offset "343f5968160953c52efb07d88c23ad15" in /home/httpd/vhosts/xyz.ch/httpdocs/plugins/system/jtaldef/jtaldef.php on line 348`

**Comment by degobbis** [comment]
Help me understand this, the line has no PHP code in the latest version:
https://github.com/joomtools/plg_system_jtaldef/blob/master/src/plugins/system/jtaldef/jtaldef.php#L348

Can You please download and reinstall the latest version again: https://github.com/joomtools/plg_system_jtaldef/releases/tag/2.0.8

**Comment by degobbis** [comment]
OK, found an error in the last package.
I built this on another computer.

Rebuilt it with a new version (2.0.9) so you can roll it out as an update.

**Comment by crimle** [comment]
I can not report any issue with plg_system_jtaldef-2.0.9.zip so far.
Thank you very much and kind regards
Chris
