### ISSUE TITLE
Problem mit lokalen Fonts

### ISSUE THREAD

**Issue by Maggi68** [JoomTools/plg_system_jtaldef#16]
Hallo,
ich habe das PLugin zum testen auf einer Seite heruntergeladen und installiert. Das funktioniert auch sehr gut, bis auf eine Seite auf der durch eine Komponente Trombinoscope Kontakte angezeigt werden. Dort erscheint oben eine Nachricht:
|Roboto" rel="stylesheet" data-jtaldef-processed="2.0.10"/>|Roboto" rel="stylesheet" /> 
siehe https://j4.gfg-fortbildung.de/index.php/kontakt
Einstellungen des plugins:
 Suche Dienst im head ja
Auch lokale CSS-Dateien ja
Die Seite bereinigen ja
Prüfe <style> im head nein
Prüfe <style> im body nein
Debug nein
Ich habe den entwickler der Komponente gefragt und er meinte, die Komponente nutzt die GDPR konformen "Bunny Fonts". Er vermutet, dass Plugin versucht diese zu finden und zu entfernen. er meint: Das Plugin berücksichtigt nicht, dass Sie im href der Links verkettete Schriftarten haben können. Es bricht dort ab, wo es zwei verkettete Schriftfamilien gibt. Ich denke, es muss vom Plugin gehandhabt werden, was in diesem speziellen Fall nicht berücksichtigt wurde.
Da ich kein entwickler bin, wollte ich Wissen, ob dies ein Problem darstellt und ob die Meldung ausgeschaltet werden kann, wenn es nur eine debug Meldung ist?
Vielen Dank
Maggi

I downloaded and installed the plugin on a site to test it. This also works very well, except for one page on which a Trombinoscope component displays contacts. A message appears at the top:
|Roboto" rel="stylesheet" data-jtaldef-processed="2.0.10"/>|Roboto" rel="stylesheet" /> 
siehe https://j4.gfg-fortbildung.de/index.php/kontakt
Einstellungen des plugins:
 Suche Dienst im head ja
Auch lokale CSS-Dateien ja
Die Seite bereinigen ja
Prüfe <style> im head nein
Prüfe <style> im body nein
Debug nein
I asked the developer of the component and he said the component uses the GDPR compliant “bunny fonts”. He suspects that the plugin is trying to find and remove them. 
Now he told me: the plugin does not take into account that you can have concatenated fonts in the links' href.
It breaks on <link href="https://fonts.bunny.net/css?family=Fauna-One|Roboto" rel="stylesheet" />
where there are 2 concatenated font families.
I guess it has to be handled by the plugin, which did not account for this particular case.

Since I'm not a developer, I wanted to know if this is a problem and if the message can be turned off if it's just a debug message?

**Comment by degobbis** [comment]
Hallo Maggi,

entschuldige die späte Antwort, Vorweihnachtszeit ;-)

Zu deinem Problem:
Eigentlich sollte mein Plugin auf die URL überhaupt nicht reagieren.

Da ich die Erweiterung, welche Du da verwendest, nicht kenne, lässt es sich für mich schwer sagen, was das Problem sein könnte.
Für eine Analyse des Problems ist ein Eingreifen während der Verarbeitung nötig (auch Debugging genannt), was im besten Fall eine Kopie der Webseite erforderlich macht. Das was Du als "Debug Meldung" interpretierst, ist eine einfache Textausgabe, die sich so nicht ausblenden lässt.

Gruß

**Comment by Maggi68** [comment]
Hallo Guido,

danke für die Antwort. Der Entwickler der anderen Erweiterung hat es sich nochmal angeschaut in der Zwischenzeit und er hat nun die Roboto Fonts in dieser Erweiterung deaktiviert...

"...remove Roboto from the extension, the font is already loaded from your template, no need for this extra call.
That will remove the concatenation and avoid the issue"

Jetzt wird die Meldung auch nicht mehr angezeigt. Für mich ist das nun so in Ordnung.
Solle noch bedarf zur Analyse sein, bitte Bescheid sagen.
Danke und Grüße

**Comment by degobbis** [comment]
Hallo Maggi,
es wäre schon interessant herauszufinden, warum es zu dieser fehlerhaften Ersetzung kommt.

Wenn Du auf [Mattermost (Gruppenchat für die Joomla Community)](https://joom.la/chat) bist, schreib mich einfach mal an.

Gruß

**Comment by Maggi68** [comment]
Nein bin ich leider nicht.... andere Möglichkeit?

**Comment by degobbis** [comment]
Nur noch Discord.

**Comment by Maggi68** [comment]
sorry auch nicht... :-( wie kommt man in die Mattermost Gruppe?

**Comment by degobbis** [comment]
Dem Link folgen, einen Account bei Joomla anlegen und dann sollte das klappen.
Der Link https://joom.la/chat kann dann immer als Aufruf zur Oberfläche verwendet werden, auch am Smartphone in der App.

**Comment by Maggi68** [comment]
Sorry...
dann komme ich dort hin...:Contact your workspace admin
To access your team's workspace, contact your workspace admin. If you've been invited already, check your email inbox for a Mattermost workspace invite.

**Comment by degobbis** [comment]
https://joomlacommunity.cloud.mattermost.com/signup_user_complete/?id=sujbzp69fpbnbkaf3hz6tkdtmy&md=link&sbr=su
