### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by pklinke** [JoomTools/plg_system_jtaldef#17]
I have update a site from J3.10 to 4.4.2.
Now I want to install this extension but this fails:

JInstaller: :Install: Die XML-Installationsdatei konnte nicht gefunden werden.
Das Joomla-Paket kann nicht wie andere Erweiterungen installiert werden. Hierfür muss die [Joomla-Update-Komponente](https://xxxxxx.xxxxxx.de/administrator/index.php?option=com_joomlaupdate) genutzt werden..

I tried both files for 4.42, full package and update package.

**Comment by degobbis** [comment]
Das liest sich aber eher danach, als würdest du versuchen das Joomla Paket über den Erweiterungsinstaller zu installieren. Mein Paket hat keine Versionsnummer mit 4.42.

**Comment by pklinke** [comment]
Da hat man mir das falsche File in die Hand gedrückt.
Jetzt selbst download und schon geht's ....
