### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by jam1974** [JoomTools/plg_system_jtaldef#3]
Hallo, 1.0.8 verursacht auch Probleme mit dem Asteroid-Framework.

**Comment by degobbis** [comment]
Hallo @jam1974 
Es ist mit dem tp_ice von joomlaPlates getestet und lief ohne Probleme.
Das verwendet auch das Atroid Framework v2.5.17.

Gibt es einen Link zum ansehen?
Bist Du auch auf RingCentral (Glip) oder Discord?

**Comment by jam1974** [comment]
RingCentral (Glip) oder Discord nutze ich nicht. Ich werde Dich über das Forum (joomla.de) anschreiben.

**Comment by degobbis** [comment]
Konnte nun den Fehler reproduzieren und mit Version 1.0.9 beheben.

Danke fürs Reporten.
