### ISSUE TITLE
Fontawesome

### ISSUE THREAD

**Issue by drfuture** [JoomTools/plg_system_jtaldef#5]
Hi, 
this is a very cool Plugin and works impressiv.
you wrote you would like to support other content then only googleFont. I have a plugin that includes fontawesome and it would be nice to host this localy too.

<link data-jtaldef="processed" href="https://use.fontawesome.com/releases/v6.0.0/css/all.css" data-version="6.0.0" rel="stylesheet" type="text/css">

is it possible to spent a coffee ? ;)

**Comment by harrypotter06** [comment]
> this is a very cool Plugin and works impressiv.

Can i test it?

**Comment by degobbis** [comment]
@harrypotter06 I think you misunderstood him. He is calling to implement the automatic downloading of fontawesome to this plugin as a feature request.

**Comment by degobbis** [comment]
@drfuture Yes is planned, but at the moment I don't have the time to implement new features.

**Comment by degobbis** [comment]
@drfuture I need your help.
Should you have an account with Fontawesome, I need the list of CDN's offered and the structure of the URL to include in the website.

Very important is, not the embedding via JS, because I can't intercept it and also can't replace it.

**Comment by degobbis** [comment]
@drfuture 
Work is in progress, see the branch [feature/fontawesome](https://github.com/joomtools/plg_system_jtaldef/tree/feature/fontawesome)

**Comment by drfuture** [comment]
thx for starting :)

im sorry, i have not an account at fontawesome; i only have a site where some plugins includes fontawesom by <script> Tag from https://use.fontawesome.com/*.... after this domain there is a custom part for every include-tag.

**Comment by degobbis** [comment]
@drfuture 
Ok, the first developer version is ready to test.
Can You do this please?
Here is the testversion for installation: [plg_system_jtaldef-1.0.14-dev.zip](https://github.com/joomtools/plg_system_jtaldef/files/9473603/plg_system_jtaldef-1.0.14-dev.zip)
I'm waiting for feedback.
Thx.

**Comment by drfuture** [comment]
@degobbis thx a lot, the external url is replaced correct (use.fontawesome.com) and replaced by a local one.

**Comment by degobbis** [comment]
Because I had to fix a bug in the current version, I made a new version for the plugin with the Fontawesome replacement.

Here is the download of the new version: 
[plg_system_jtaldef-2.0.0-dev.zip](https://github.com/joomtools/plg_system_jtaldef/files/9600717/plg_system_jtaldef-2.0.0-dev.zip)

The fix is also already implemented here.

**Comment by degobbis** [comment]
@drfuture Can you please test, if the latest [version 2.0.1](https://github.com/joomtools/plg_system_jtaldef/releases) also works for You?
So we can close this issue :-)
