### ISSUE TITLE
No installation possible

### ISSUE THREAD

**Issue by sati-1** [JoomTools/plg_system_jtaldef#6]
we use:
Joomla: 3.10.11
PHP: 7.4.30
Database: mysql 5.5.5-10.5.17

During the installation we get the following messages:
Warning / JInstaller: :Install: The Joomla! XML installer file could not be found.
Error / The manifest file could not be found.

Other extensions can be easily installed
![warning-error](https://user-images.githubusercontent.com/111606785/185694033-e18a4a97-45e2-41c8-9c32-bc2731723f56.jpg)
.

**Comment by degobbis** [comment]
You are probably Usingen the wrong  installation package.

Please go to the latest release and download the plg_system_jtaldef-1.x.x.zip

19.08.2022 21:34:15 sati-1 ***@***.***>:

**Comment by sati-1** [comment]
You're right - I used the wrong file -> plg_system_jtaldef-master.zip
The installation works with the plg_system_jtaldef-1.0.12.zip

Thanks

**Comment by sati-1** [comment]
Before the installation the Font-Checker "https://sicher3.de/google-fonts-checker/" found 9 entries -> before.jpg
After the installation the Font-Checker still finds an entry -> after.jpg
Is an entry overlooked or not found here?

![before](https://user-images.githubusercontent.com/111606785/185735961-8ce9c5af-b613-40d2-845c-d6e3b7c977b6.jpg)
![after](https://user-images.githubusercontent.com/111606785/185735963-39b30702-4afc-4132-b843-f807a6852f12.jpg)

**Comment by degobbis** [comment]
It will be loaded by Youtube after the site is loaded.
