### ISSUE TITLE
does not function

### ISSUE THREAD

**Issue by msebastian100** [JoomTools/plg_system_jtaldef#8]
The plugin has been installed and is active
It has no settings options
after the installation of plugin I have checked my page for Google front but it is still found google front.

**Comment by degobbis** [comment]
Wich Version is installed? 
Can You post a Screenshot of the Plugin configuration site?
Is there an error message (error reporting: maximum and debug mode on, in global configuration)

**Comment by msebastian100** [comment]
Hello,
Thanks for the quick reply :)

i have downloaded the now version from github.
The plugin was also installed 
but I don't know if it is installed correctly...



greetings sebastian m.

**Comment by degobbis** [comment]
It seems You have not installed a correct version.
Please go to the latest releases and download and install the installation package.
https://github.com/joomtools/plg_system_jtaldef/releases

**Comment by msebastian100** [comment]
Hello,
Yes I just noticed that too. I had from github the "plg_system_jtaldef-master.zip".

I had now also made another check of the website.
 "No reloading fonts found! Yeah, we couldn't find any fonts being reloaded by Google. No action is required at this time."


Thank you for this very good and useful plugin :-)

Greetings Sebastian M.

**Comment by degobbis** [comment]
You are welcome :-)
