### ISSUE TITLE
webfont.js detection

### ISSUE THREAD

**Issue by lenusch** [JoomTools/plg_system_jtaldef#9]
Hi, 
Plugins looks great but doesn't work with https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js?ver=2.7.9 which is loading then: https://fonts.googleapis.com/css?family=Montserrat:700 for example.

**Comment by degobbis** [comment]
Replacing Google Fonts, which are reloaded via Javascript, is not supported.
This is not offered on https://fonts.google.com, in the FAQs or in the API doc.

The offered possibilities can also be found in the description.
https://github.com/joomtools/plg_system_jtaldef
